server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/{test}
  #    username: root
  #    password: 1q2w3e4r
  #    driver-class-name: com.mysql.jdbc.Driver
#  data:
#    rest:
#      base-path: /api
#      default-page-size: 10
#      max-page-size: 10
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/web
    username: sa
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB