server:
  port: 8088
spring:
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434312685058-nhaili5ul2aplhc1u9u5985hvdtnubva.apps.googleusercontent.com
            client-secret: Y0irvYTgmOfBnZc4dLaW_VBC
          facebook:
            client-id: 793640824605119
            client-secret: 7c94b14fc4bb5916bcb284aabaf75a97
custom:
  oauth2:
    kakao:
      client-id: a68841ed5a6f8360629cabb5e7aea580