server:
  port: 8088
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/{test}
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
    path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434312685058-nhaili5ul2aplhc1u9u5985hvdtnubva.apps.googleusercontent.com
            client-secret: Y0irvYTgmOfBnZc4dLaW_VBC
          facebook:
            client-id: 793640824605119
            client-secret: 7c94b14fc4bb5916bcb284aabaf75a97
custom:
  oauth2:
    kakao:
      client-id: a68841ed5a6f8360629cabb5e7aea580